### ISSUE TITLE
Problem with installing electron

### ISSUE THREAD

**Issue by StefanMallia** [notfound4/Duelyst-Launcher#1]
Fails on: `npm install electron-prebuilt@${ELECTRON_VERSION} --save`

npm ERR! electron-prebuilt@1.1.3 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.1.3 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.5.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-prebuilt@1.1.3" "--save"
npm ERR! cwd /media/stefan/duelyst-v1.72.0/resources/app
npm ERR! node -v v4.3.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /media/stefan/duelyst-v1.72.0/resources/app/npm-debug.log
npm ERR! not ok code 0

**Comment by StefanMallia** [comment]
The problem seems to be due to npm using a `node` command which should be `nodejs`
solution:
sudo apt-get install nodejs-legacy

solution found here:
https://github.com/electron-userland/electron-prebuilt/issues/70

**Comment by notfound4** [comment]
should be fixed
